/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ThreatIntelFeed } from "./ThreatIntelFeed";
export * as factories from "./factories";
export { ThreatIntelFeed__factory } from "./factories/ThreatIntelFeed__factory";
