/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ThreatIntelFeed {
  export type IndicatorStruct = {
    id: BigNumberish;
    name: string;
    value: string;
    types: string;
    confidence: BigNumberish;
    source: AddressLike;
    first_seen: BigNumberish;
    last_seen: BigNumberish;
    tags: string[];
    description: string;
  };

  export type IndicatorStructOutput = [
    id: bigint,
    name: string,
    value: string,
    types: string,
    confidence: bigint,
    source: string,
    first_seen: bigint,
    last_seen: bigint,
    tags: string[],
    description: string
  ] & {
    id: bigint;
    name: string;
    value: string;
    types: string;
    confidence: bigint;
    source: string;
    first_seen: bigint;
    last_seen: bigint;
    tags: string[];
    description: string;
  };
}

export interface ThreatIntelFeedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIndicator"
      | "counter"
      | "decrementConfidence"
      | "delIndicators"
      | "getIndicator"
      | "getIndicators"
      | "incrementConfidence"
      | "indicators"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "IndicatorAdded" | "confidenceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIndicator",
    values: [string, string, string, string[], string]
  ): string;
  encodeFunctionData(functionFragment: "counter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decrementConfidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delIndicators",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIndicator",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIndicators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "incrementConfidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "indicators",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addIndicator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "counter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decrementConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delIndicators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIndicator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIndicators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "indicators", data: BytesLike): Result;
}

export namespace IndicatorAddedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    value: string,
    types: string,
    confidence: BigNumberish,
    source: AddressLike,
    tags: string[],
    description: string
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    value: string,
    types: string,
    confidence: bigint,
    source: string,
    tags: string[],
    description: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    value: string;
    types: string;
    confidence: bigint;
    source: string;
    tags: string[];
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace confidenceUpdatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    confidence: BigNumberish,
    voter: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    name: string,
    confidence: bigint,
    voter: string
  ];
  export interface OutputObject {
    id: bigint;
    name: string;
    confidence: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ThreatIntelFeed extends BaseContract {
  connect(runner?: ContractRunner | null): ThreatIntelFeed;
  waitForDeployment(): Promise<this>;

  interface: ThreatIntelFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIndicator: TypedContractMethod<
    [
      _name: string,
      _value: string,
      _types: string,
      _tags: string[],
      _description: string
    ],
    [void],
    "nonpayable"
  >;

  counter: TypedContractMethod<[], [bigint], "view">;

  decrementConfidence: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  delIndicators: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getIndicator: TypedContractMethod<
    [id: BigNumberish],
    [ThreatIntelFeed.IndicatorStructOutput],
    "view"
  >;

  getIndicators: TypedContractMethod<
    [],
    [ThreatIntelFeed.IndicatorStructOutput[]],
    "view"
  >;

  incrementConfidence: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  indicators: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        name: string;
        value: string;
        types: string;
        confidence: bigint;
        source: string;
        first_seen: bigint;
        last_seen: bigint;
        description: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIndicator"
  ): TypedContractMethod<
    [
      _name: string,
      _value: string,
      _types: string,
      _tags: string[],
      _description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "counter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decrementConfidence"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delIndicators"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getIndicator"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ThreatIntelFeed.IndicatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIndicators"
  ): TypedContractMethod<[], [ThreatIntelFeed.IndicatorStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "incrementConfidence"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "indicators"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        name: string;
        value: string;
        types: string;
        confidence: bigint;
        source: string;
        first_seen: bigint;
        last_seen: bigint;
        description: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "IndicatorAdded"
  ): TypedContractEvent<
    IndicatorAddedEvent.InputTuple,
    IndicatorAddedEvent.OutputTuple,
    IndicatorAddedEvent.OutputObject
  >;
  getEvent(
    key: "confidenceUpdated"
  ): TypedContractEvent<
    confidenceUpdatedEvent.InputTuple,
    confidenceUpdatedEvent.OutputTuple,
    confidenceUpdatedEvent.OutputObject
  >;

  filters: {
    "IndicatorAdded(uint256,string,string,string,uint256,address,string[],string)": TypedContractEvent<
      IndicatorAddedEvent.InputTuple,
      IndicatorAddedEvent.OutputTuple,
      IndicatorAddedEvent.OutputObject
    >;
    IndicatorAdded: TypedContractEvent<
      IndicatorAddedEvent.InputTuple,
      IndicatorAddedEvent.OutputTuple,
      IndicatorAddedEvent.OutputObject
    >;

    "confidenceUpdated(uint256,string,int256,address)": TypedContractEvent<
      confidenceUpdatedEvent.InputTuple,
      confidenceUpdatedEvent.OutputTuple,
      confidenceUpdatedEvent.OutputObject
    >;
    confidenceUpdated: TypedContractEvent<
      confidenceUpdatedEvent.InputTuple,
      confidenceUpdatedEvent.OutputTuple,
      confidenceUpdatedEvent.OutputObject
    >;
  };
}
